import { CATEGORIE_TOOL, etichetta } from "@/lib/taxonomy";

export type Prezzo = "gratis" | "freemium" | "a pagamento";

export type Tool = {
  slug: string;
  name: string;
  /** Una riga: è quella che compare sulla scheda in griglia. */
  tagline: string;
  /** Due o tre frasi: apre la pagina di dettaglio. */
  description: string;
  /** La prima è la categoria principale, usata nel breadcrumb. */
  categories: string[];
  /** Colore del marchio, usato per la tessera del logo. */
  color: string;
  url: string;
  pricing: Prezzo;
  pricingNote: string | null;
  features: string[];
  useCases: string[];
  pros: string[];
  cons: string[];
  /** 0-100, ordina la vista "Più popolari". */
  popularity: number;
  featured: boolean;
};

export const TOOLS: Tool[] = [
  {
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "L'assistente generalista per scrittura, ricerca e analisi",
    description: "Il modello di OpenAI resta lo strumento più veloce da mettere in mano a un team che non ha mai usato l'AI: scrive, riassume, estrae dati dai documenti e ora esegue compiti in autonomia.",
    categories: ["assistenti","agenti","contenuti","ricerca"],
    color: "#10A37F",
    url: "https://chatgpt.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Plus 23 $/mese · Business da 25 $/utente",
    features: ["Analisi di PDF, fogli di calcolo e immagini","GPT personalizzati addestrati sui documenti aziendali","Ricerca web con citazioni","Modalità agente che completa compiti multi-passo","Connettori verso Drive, SharePoint e Gmail"],
    useCases: ["Prima stesura di preventivi e proposte commerciali","Estrazione di dati da fatture e ordini in PDF","Risposte standard alle email ricorrenti","Analisi di un export CSV senza aprire Excel"],
    pros: ["Curva di apprendimento quasi nulla","Ecosistema di integrazioni più ampio del mercato","Il piano Business esclude i dati dall'addestramento"],
    cons: ["Sul piano gratuito i dati alimentano l'addestramento","Costo per utente che cresce in fretta oltre le 10 persone","Server fuori dall'UE salvo accordi specifici"],
    popularity: 99,
    featured: true,
  },
  {
    slug: "claude",
    name: "Claude",
    tagline: "Il modello che regge i documenti lunghi senza perdere il filo",
    description: "Anthropic ha costruito Claude attorno a due qualità che contano in azienda: una finestra di contesto molto ampia e una scrittura che non suona artificiale. È lo strumento giusto quando il materiale di partenza è un contratto da ottanta pagine.",
    categories: ["assistenti","agenti","sviluppo","contenuti"],
    color: "#D97757",
    url: "https://claude.ai",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Pro 18 €/mese · Team da 25 €/utente",
    features: ["Finestra di contesto da centinaia di pagine","Progetti con knowledge base condivisa","Artifacts per generare documenti e interfacce","Connettori MCP verso strumenti aziendali","Skill riutilizzabili per compiti ripetitivi"],
    useCases: ["Analisi di contratti e capitolati di gara","Riscrittura di documentazione tecnica","Audit di un intero repository di codice","Sintesi di verbali e trascrizioni di riunione"],
    pros: ["Qualità di scrittura in italiano superiore alla media","Non usa le conversazioni per l'addestramento sui piani a pagamento","Ottimo su compiti che richiedono contesto lungo"],
    cons: ["Generazione di immagini assente","Limiti d'uso più stretti sul piano gratuito","Meno integrazioni native rispetto a ChatGPT"],
    popularity: 96,
    featured: true,
  },
  {
    slug: "gemini",
    name: "Gemini",
    tagline: "L'AI di Google dentro Gmail, Drive e Documenti",
    description: "Il vantaggio di Gemini non è il modello in sé ma dove vive: se l'azienda lavora su Workspace, l'assistente è già dentro la casella di posta e dentro i fogli, senza copiare e incollare nulla.",
    categories: ["assistenti","ricerca","contenuti"],
    color: "#8E75B2",
    url: "https://gemini.google.com",
    pricing: "freemium",
    pricingNote: "Gratis · Google AI Pro 21,99 €/mese · incluso in alcuni piani Workspace",
    features: ["Integrazione nativa con Gmail, Documenti e Fogli","Deep Research su fonti web con report strutturato","Analisi di video e audio caricati","Generazione immagini con Nano Banana","Contesto molto ampio sui file di Drive"],
    useCases: ["Riassunto automatico dei thread di posta","Compilazione di fogli a partire da testo libero","Ricerca di mercato con fonti verificabili","Bozze di risposta dentro Gmail"],
    pros: ["Zero attrito per chi è già su Workspace","Data residency europea configurabile su Workspace","Deep Research tra i migliori per report lunghi"],
    cons: ["Qualità disomogenea tra un rilascio e l'altro","Funzioni migliori legate ai piani Workspace superiori","Interfaccia che cambia spesso"],
    popularity: 92,
    featured: true,
  },
  {
    slug: "copilot",
    name: "Microsoft Copilot",
    tagline: "L'assistente dentro Word, Excel, Outlook e Teams",
    description: "Per le aziende che vivono su Microsoft 365, Copilot è la strada di minor resistenza: nessun nuovo strumento da far adottare, l'AI compare dove le persone lavorano già.",
    categories: ["produttivita","assistenti","operations"],
    color: "#0078D4",
    url: "https://copilot.microsoft.com",
    pricing: "a pagamento",
    pricingNote: "Copilot per Microsoft 365 circa 30 $/utente/mese",
    features: ["Generazione di documenti Word dai file esistenti","Formule e analisi in Excel a linguaggio naturale","Riassunto delle riunioni Teams con azioni","Bozze e sintesi in Outlook","Copilot Studio per agenti interni"],
    useCases: ["Verbali automatici delle riunioni con i punti d'azione","Analisi di un foglio vendite senza tabelle pivot","Prima stesura di relazioni a partire da più documenti","Triage della posta in entrata"],
    pros: ["Rispetta i permessi già configurati su SharePoint","Dati trattati dentro il tenant aziendale","Nessun cambio di abitudini per gli utenti"],
    cons: ["Prezzo per utente tra i più alti","Richiede una gerarchia di permessi già pulita","Resa variabile tra le diverse app"],
    popularity: 88,
    featured: false,
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    tagline: "Motore di risposta con fonti citate riga per riga",
    description: "Non è un chatbot: è un motore di ricerca che risponde. La differenza pratica è che ogni affermazione porta il link alla fonte, quindi il risultato è verificabile e usabile in un documento.",
    categories: ["ricerca","assistenti","dati"],
    color: "#1FB8CD",
    url: "https://www.perplexity.ai",
    pricing: "freemium",
    pricingNote: "Gratis · Pro 20 $/mese · Enterprise da 40 $/utente",
    features: ["Citazioni puntuali su ogni risposta","Spazi condivisi con documenti caricati","Ricerca ristretta ad accademico, social o finanza","Deep Research con report multi-fonte","Browser Comet con agente integrato"],
    useCases: ["Ricerca di mercato prima di una call commerciale","Verifica di normative e scadenze","Scouting di fornitori e concorrenti","Raccolta fonti per un articolo"],
    pros: ["Verificabilità: ogni frase ha un link","Molto più veloce di una ricerca manuale","Buona copertura delle fonti italiane"],
    cons: ["Meno adatto a compiti creativi o di scrittura lunga","Qualità legata a cosa è indicizzato","Le fonti vanno comunque controllate"],
    popularity: 90,
    featured: true,
  },
  {
    slug: "grok",
    name: "Grok",
    tagline: "Il modello di xAI con accesso diretto al flusso di X",
    description: "Grok vale soprattutto per una cosa che gli altri non hanno: legge X in tempo reale. Per chi fa monitoraggio di marca o segue un settore che si muove sui social, è un canale che gli altri modelli non vedono.",
    categories: ["assistenti","ricerca","marketing"],
    color: "#111111",
    url: "https://grok.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · SuperGrok 30 $/mese",
    features: ["Accesso in tempo reale ai contenuti di X","Generazione immagini integrata","Modalità di ragionamento estesa","API con prezzi competitivi"],
    useCases: ["Monitoraggio delle conversazioni su un marchio","Analisi di sentiment su un tema di settore","Ricerca di trend prima che arrivino sui media"],
    pros: ["Unico con accesso nativo a X","Prezzi API aggressivi","Risposte rapide"],
    cons: ["Tono non sempre adatto a un contesto aziendale","Meno affidabile su compiti strutturati","Ecosistema di integrazioni limitato"],
    popularity: 74,
    featured: false,
  },
  {
    slug: "mistral",
    name: "Mistral · Le Chat",
    tagline: "Il modello europeo, ospitabile anche on premise",
    description: "Mistral è francese e i suoi modelli si possono far girare su server propri. Per le aziende che non vogliono mandare dati fuori dall'Unione, o che hanno vincoli contrattuali sul trattamento, è spesso l'unica opzione praticabile.",
    categories: ["assistenti","sviluppo","operations"],
    color: "#FA520F",
    url: "https://chat.mistral.ai",
    pricing: "freemium",
    pricingNote: "Le Chat gratis · Pro 14,99 €/mese · licenze on premise su richiesta",
    features: ["Modelli con pesi aperti installabili in locale","Infrastruttura e dati nell'Unione Europea","Agenti con esecuzione di codice e ricerca","API compatibile con lo standard OpenAI"],
    useCases: ["Assistente interno su dati che non possono uscire","Classificazione di documenti riservati","Sostituzione drop-in di API americane"],
    pros: ["Conformità e residenza dei dati in UE","Costi API bassi","Possibilità di autoinstallazione"],
    cons: ["Prestazioni sotto ai modelli di punta su compiti complessi","Ecosistema di strumenti più piccolo","Meno materiale formativo in italiano"],
    popularity: 71,
    featured: false,
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    tagline: "Prestazioni alte a costo API quasi nullo",
    description: "DeepSeek ha spostato il prezzo di riferimento dell'inferenza. Per volumi alti e compiti ripetitivi il conto cambia di un ordine di grandezza rispetto ai concorrenti occidentali.",
    categories: ["assistenti","sviluppo"],
    color: "#5786FE",
    url: "https://chat.deepseek.com",
    pricing: "gratis",
    pricingNote: "Chat gratuita · API tra le più economiche del mercato",
    features: ["Modelli con pesi aperti","Ragionamento esplicito passo per passo","Costo per milione di token molto basso","Ottimo su matematica e codice"],
    useCases: ["Classificazione di migliaia di record","Arricchimento massivo di anagrafiche","Prototipazione a basso costo"],
    pros: ["Rapporto qualità/prezzo senza rivali","Pesi scaricabili e installabili in locale"],
    cons: ["Server in Cina se si usa il servizio ospitato: da valutare con il DPO","Filtri sui contenuti su alcuni temi","Supporto aziendale limitato"],
    popularity: 68,
    featured: false,
  },
  {
    slug: "notebooklm",
    name: "NotebookLM",
    tagline: "Assistente di ricerca che risponde solo sui tuoi documenti",
    description: "Carichi le fonti, e da quel momento il modello risponde solo su quelle. È il modo più rapido per costruire una base di conoscenza interrogabile su manuali, contratti o normative senza montare nulla.",
    categories: ["ricerca","produttivita","formazione"],
    color: "#4285F4",
    url: "https://notebooklm.google.com",
    pricing: "freemium",
    pricingNote: "Gratis · Plus incluso in Google AI Pro",
    features: ["Risposte ancorate esclusivamente alle fonti caricate","Citazione del passaggio esatto","Panoramica audio in formato podcast","Mappe mentali e riassunti automatici","Fino a 50 fonti per taccuino"],
    useCases: ["Manuale operativo interrogabile per i nuovi assunti","Analisi comparata di più capitolati","Studio di una normativa con riferimenti puntuali"],
    pros: ["Nessuna invenzione: risponde solo dalle fonti","Gratuito nella versione base","Ottimo per la formazione interna"],
    cons: ["Non naviga il web","Limite al numero di fonti","Nessun controllo granulare di condivisione"],
    popularity: 79,
    featured: false,
  },
  {
    slug: "n8n",
    name: "n8n",
    tagline: "Automazioni installabili sul proprio server, senza limiti di operazioni",
    description: "È la piattaforma che consigliamo più spesso alle PMI italiane: si installa su un server proprio, i dati non escono, e il costo non cresce con il numero di esecuzioni. Il prezzo da pagare è un'ora di configurazione iniziale.",
    categories: ["automazione","agenti","no-code","operations"],
    color: "#EA4B71",
    url: "https://n8n.io",
    pricing: "freemium",
    pricingNote: "Self-hosted gratuito · Cloud da 24 €/mese",
    features: ["Oltre 400 integrazioni pronte","Nodi AI Agent con memoria e strumenti","Nodo codice JavaScript o Python","Installazione su Docker in pochi minuti","Versionamento dei flussi"],
    useCases: ["Ordine che arriva via email e finisce nel gestionale","Lead dal sito smistato al commerciale giusto","Report settimanale generato e inviato in automatico","Chatbot WhatsApp collegato al catalogo"],
    pros: ["Dati sul proprio server: conformità semplice","Nessun costo per esecuzione se auto-installato","Il nodo codice toglie ogni limite"],
    cons: ["Richiede un minimo di competenza tecnica","Manutenzione dell'infrastruttura a carico dell'azienda","Interfaccia meno guidata dei concorrenti"],
    popularity: 91,
    featured: true,
  },
  {
    slug: "make",
    name: "Make",
    tagline: "Automazioni visuali con logica complessa senza scrivere codice",
    description: "Make è il compromesso migliore tra potenza e accessibilità: gestisce condizioni, cicli e gestione degli errori con un editor visuale che una persona non tecnica riesce davvero a usare.",
    categories: ["automazione","no-code","operations"],
    color: "#6D00CC",
    url: "https://www.make.com",
    pricing: "freemium",
    pricingNote: "Gratis 1.000 operazioni/mese · Core 9 $/mese",
    features: ["Editor visuale a scenari","Router, filtri e iteratori","Oltre 2.000 app collegate","Ripetizione automatica in caso di errore","Modulo HTTP per qualsiasi API"],
    useCases: ["Sincronizzazione tra e-commerce e gestionale","Notifiche interne su eventi del CRM","Elaborazione batch di file da una cartella"],
    pros: ["Il migliore per logiche condizionali senza codice","Prezzo d'ingresso basso","Documentazione chiara"],
    cons: ["Il conteggio a operazioni sorprende sui volumi alti","Dati elaborati su cloud del fornitore","Debug faticoso sugli scenari lunghi"],
    popularity: 84,
    featured: false,
  },
  {
    slug: "zapier",
    name: "Zapier",
    tagline: "Il collegamento più rapido tra due applicazioni",
    description: "Zapier resta lo strumento con il maggior numero di integrazioni esistenti. Per un collegamento semplice tra due software si configura in dieci minuti; per una logica articolata conviene guardare altrove.",
    categories: ["automazione","no-code"],
    color: "#FF4F00",
    url: "https://zapier.com",
    pricing: "freemium",
    pricingNote: "Gratis 100 attività/mese · Professional da 19,99 $/mese",
    features: ["Oltre 7.000 applicazioni integrate","Zap a più passaggi","Tabelle e interfacce interne","Agenti Zapier per compiti autonomi"],
    useCases: ["Modulo del sito che crea un contatto nel CRM","Fattura firmata che avvia l'onboarding","Backup automatico degli allegati su Drive"],
    pros: ["Catalogo di integrazioni imbattibile","Configurazione alla portata di chiunque"],
    cons: ["Costo che sale rapidamente con i volumi","Logica condizionale limitata sui piani bassi","Poco adatto a flussi con molti passaggi"],
    popularity: 82,
    featured: false,
  },
  {
    slug: "lindy",
    name: "Lindy",
    tagline: "Agenti AI che gestiscono posta, agenda e follow-up",
    description: "Lindy costruisce assistenti che lavorano in background: leggono la casella, qualificano le richieste, prenotano in agenda e aggiornano il CRM senza che nessuno apra un'interfaccia.",
    categories: ["agenti","automazione","vendite"],
    color: "#4F46E5",
    url: "https://www.lindy.ai",
    pricing: "a pagamento",
    pricingNote: "Da 49,99 $/mese",
    features: ["Agenti attivati da email, calendario o webhook","Memoria persistente tra le esecuzioni","Squadre di agenti che si passano il lavoro","Telefonate in entrata e in uscita"],
    useCases: ["Qualificazione automatica dei lead in arrivo","Prenotazione appuntamenti via email","Recupero dei preventivi senza risposta"],
    pros: ["Pensato per compiti reali di ufficio, non per demo","Non richiede competenze tecniche"],
    cons: ["Nessun piano gratuito","Serve supervisione nelle prime settimane","Dati trattati fuori dall'UE"],
    popularity: 69,
    featured: false,
  },
  {
    slug: "manus",
    name: "Manus",
    tagline: "Agente autonomo che porta a termine ricerche e deliverable",
    description: "Gli dai un obiettivo, lui apre il browser, raccoglie, elabora e consegna un file. Funziona bene sui compiti di ricerca lunghi che nessuno in azienda ha tempo di fare.",
    categories: ["agenti","ricerca","dati"],
    color: "#1A1A1A",
    url: "https://manus.im",
    pricing: "freemium",
    pricingNote: "Crediti gratuiti · piani da 19 $/mese",
    features: ["Navigazione web autonoma","Esecuzione di codice in ambiente isolato","Consegna di file pronti: fogli, presentazioni, siti","Esecuzione in background"],
    useCases: ["Mappatura dei concorrenti di un settore","Costruzione di una lista prospect verificata","Analisi di un dataset pubblico"],
    pros: ["Chiude compiti che gli assistenti normali lasciano a metà","Consegna file utilizzabili"],
    cons: ["Consumo di crediti poco prevedibile","Tempi lunghi sui compiti complessi","Risultati da verificare sempre"],
    popularity: 66,
    featured: false,
  },
  {
    slug: "gumloop",
    name: "Gumloop",
    tagline: "Flussi AI no-code per elaborare dati in blocco",
    description: "Gumloop è pensato per il lavoro ripetitivo su liste: prendi cento URL, cento CV o cento schede prodotto e li fai attraversare tutti dallo stesso flusso.",
    categories: ["automazione","agenti","dati","marketing"],
    color: "#7C3AED",
    url: "https://www.gumloop.com",
    pricing: "freemium",
    pricingNote: "Piano gratuito con crediti · da 97 $/mese",
    features: ["Elaborazione in blocco su liste e fogli","Scraping web integrato","Estensione browser per raccogliere dati","Libreria di flussi pronti"],
    useCases: ["Arricchimento di una lista di aziende target","Screening automatico delle candidature","Generazione di schede prodotto per un catalogo"],
    pros: ["Il migliore sul lavoro batch","Non serve saper programmare"],
    cons: ["Salto di prezzo importante dopo il piano gratuito","Meno integrazioni dirette dei concorrenti"],
    popularity: 61,
    featured: false,
  },
  {
    slug: "relevance-ai",
    name: "Relevance AI",
    tagline: "Squadre di agenti con ruoli, per vendite e operazioni",
    description: "L'idea è organizzare gli agenti come si organizza un team: un ruolo, una serie di strumenti, istruzioni scritte. Funziona bene sui processi commerciali ripetitivi.",
    categories: ["agenti","vendite","operations"],
    color: "#6366F1",
    url: "https://relevanceai.com",
    pricing: "freemium",
    pricingNote: "Piano gratuito · Pro da 19 $/mese",
    features: ["Agenti con ruolo e strumenti assegnati","Squadre che si coordinano","Integrazione con i principali CRM","Attivazione via webhook o pianificata"],
    useCases: ["Ricerca sui prospect prima della chiamata","Aggiornamento automatico delle schede CRM","Smistamento delle richieste in entrata"],
    pros: ["Modello mentale chiaro per chi viene dal commerciale","Piano gratuito utilizzabile"],
    cons: ["Configurazione iniziale lunga","Documentazione a tratti scarna"],
    popularity: 57,
    featured: false,
  },
  {
    slug: "comet",
    name: "Comet",
    tagline: "Il browser di Perplexity che esegue azioni al posto tuo",
    description: "Un browser con dentro un agente: compila moduli, confronta pagine aperte, estrae tabelle e riassume quello che stai leggendo senza copiare nulla altrove.",
    categories: ["agenti","ricerca","produttivita"],
    color: "#1FB8CD",
    url: "https://comet.perplexity.ai",
    pricing: "freemium",
    pricingNote: "Gratuito · funzioni avanzate con Perplexity Pro",
    features: ["Agente che agisce sulle schede aperte","Riassunto della pagina corrente","Compilazione automatica di moduli","Confronto tra più schede"],
    useCases: ["Compilazione di portali fornitori ripetitivi","Confronto prezzi su più siti","Estrazione di tabelle da pagine web"],
    pros: ["Toglie il copia-incolla dal lavoro di ricerca","Basato su Chromium: estensioni compatibili"],
    cons: ["Da valutare con attenzione su portali con dati sensibili","Ancora instabile su alcuni siti"],
    popularity: 64,
    featured: false,
  },
  {
    slug: "claude-code",
    name: "Claude Code",
    tagline: "Assistente di sviluppo che lavora sull'intero repository",
    description: "Vive nel terminale e legge tutto il progetto prima di toccarlo. È lo strumento con cui, in pratica, si scrivono e si mantengono i progetti interni di un'azienda piccola senza un reparto IT.",
    categories: ["sviluppo","agenti"],
    color: "#D97757",
    url: "https://claude.com/claude-code",
    pricing: "a pagamento",
    pricingNote: "Incluso in Claude Pro 18 €/mese e Max",
    features: ["Comprensione dell'intero repository","Modifica di più file in una sola richiesta","Esecuzione di test e comandi","Integrazione con Git e GitHub","Sottoagenti per compiti paralleli"],
    useCases: ["Migrazione di un progetto a una versione nuova del framework","Correzione di bug su codice ereditato","Stesura della documentazione mancante","Automazione di script interni"],
    pros: ["Contesto reale su tutto il progetto","Nessun costo aggiuntivo oltre l'abbonamento","Ottimo su codebase legacy"],
    cons: ["Serve confidenza con il terminale","Il codice va sempre riletto","Limiti d'uso sui piani più bassi"],
    popularity: 89,
    featured: true,
  },
  {
    slug: "codex",
    name: "Codex",
    tagline: "L'agente di programmazione di OpenAI",
    description: "Codex esegue compiti di sviluppo in un ambiente isolato e restituisce una pull request. È pensato per delegare interi task, non per completare righe mentre scrivi.",
    categories: ["sviluppo","agenti"],
    color: "#10A37F",
    url: "https://openai.com/codex",
    pricing: "a pagamento",
    pricingNote: "Incluso nei piani ChatGPT Plus, Pro e Business",
    features: ["Esecuzione in sandbox isolata","Compiti paralleli su più branch","CLI e integrazione con l'IDE","Pull request generate in automatico"],
    useCases: ["Correzione di bug segnalati dagli utenti","Aggiornamento delle dipendenze","Scrittura dei test mancanti"],
    pros: ["Delega di compiti interi, non solo suggerimenti","Buona integrazione con GitHub"],
    cons: ["Serve un abbonamento ChatGPT a pagamento","Meno efficace su repository molto grandi"],
    popularity: 80,
    featured: false,
  },
  {
    slug: "cursor",
    name: "Cursor",
    tagline: "L'editor di codice costruito attorno all'AI",
    description: "È VS Code con l'assistente al centro invece che di lato. Per chi programma tutti i giorni resta l'ambiente più fluido tra scrittura manuale e generazione.",
    categories: ["sviluppo"],
    color: "#111111",
    url: "https://cursor.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Pro 20 $/mese",
    features: ["Modifica multi-file in linea","Indicizzazione dell'intero progetto","Modalità agente autonoma","Regole di progetto personalizzate","Compatibile con le estensioni VS Code"],
    useCases: ["Sviluppo quotidiano di applicazioni interne","Refactoring su più file","Onboarding rapido su un progetto sconosciuto"],
    pros: ["Il flusso di lavoro più curato del settore","Compatibilità totale con VS Code"],
    cons: ["Costo aggiuntivo rispetto all'abbonamento AI già in essere","Consumo di risorse elevato su progetti grandi"],
    popularity: 85,
    featured: false,
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "Il completamento di codice integrato in ogni editor",
    description: "Il più diffuso e il più discreto: suggerisce mentre scrivi, senza cambiare il modo di lavorare. Per i team già su GitHub è l'opzione con meno attrito organizzativo.",
    categories: ["sviluppo"],
    color: "#181717",
    url: "https://github.com/features/copilot",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Pro 10 $/mese · Business 19 $/utente",
    features: ["Completamento in linea in tempo reale","Chat contestuale nell'editor","Revisione automatica delle pull request","Agente che apre PR autonome","Scelta tra più modelli"],
    useCases: ["Scrittura quotidiana con meno digitazione","Revisione preliminare delle PR","Generazione dei test unitari"],
    pros: ["Integrazione con qualunque editor","Governance aziendale già pronta","Prezzo per utente contenuto"],
    cons: ["Meno autonomo degli agenti dedicati","Suggerimenti generici su codebase molto specifiche"],
    popularity: 83,
    featured: false,
  },
  {
    slug: "replit",
    name: "Replit",
    tagline: "Dall'idea all'applicazione online senza installare nulla",
    description: "Descrivi l'applicazione, Replit la costruisce, la ospita e la pubblica. È il modo più rapido per mettere online uno strumento interno quando non c'è nessuno a occuparsene.",
    categories: ["sviluppo","no-code"],
    color: "#F26207",
    url: "https://replit.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Core 20 $/mese",
    features: ["Agent che genera l'app completa","Hosting e database inclusi","Collaborazione in tempo reale","Pubblicazione con un clic"],
    useCases: ["Strumento interno di raccolta dati","Prototipo da mostrare a un cliente","Calcolatore di preventivi sul sito"],
    pros: ["Dall'idea all'URL pubblico in un'ora","Nessuna configurazione di server"],
    cons: ["Consumo di crediti rapido","Non adatto a sistemi in produzione critici"],
    popularity: 72,
    featured: false,
  },
  {
    slug: "lovable",
    name: "Lovable",
    tagline: "Applicazioni web complete descritte a parole",
    description: "Generi un'interfaccia funzionante scrivendo cosa ti serve, con database e autenticazione già collegati. Il codice resta tuo ed è esportabile.",
    categories: ["no-code","sviluppo","design"],
    color: "#FF4E88",
    url: "https://lovable.dev",
    pricing: "freemium",
    pricingNote: "Gratis con crediti · da 25 $/mese",
    features: ["Generazione di interfacce React complete","Collegamento a Supabase per dati e login","Esportazione del codice su GitHub","Anteprima in tempo reale"],
    useCases: ["Landing page con modulo collegato al CRM","Gestionale leggero per un processo interno","Portale clienti su misura"],
    pros: ["Risultati visivi curati fin dal primo passaggio","Codice esportabile: nessun vincolo con il fornitore"],
    cons: ["Crediti che si consumano in fretta durante le correzioni","Logiche complesse richiedono comunque uno sviluppatore"],
    popularity: 76,
    featured: false,
  },
  {
    slug: "v0",
    name: "v0",
    tagline: "Interfacce React generate da una descrizione o da un'immagine",
    description: "Di Vercel: descrivi un componente o carichi uno screenshot, e ottieni codice React pulito pronto da incollare nel progetto.",
    categories: ["no-code","design","sviluppo"],
    color: "#111111",
    url: "https://v0.app",
    pricing: "freemium",
    pricingNote: "Gratis con crediti · da 20 $/mese",
    features: ["Da immagine a componente funzionante","Codice React e Tailwind pronto","Pubblicazione immediata su Vercel","Iterazione conversazionale"],
    useCases: ["Prototipazione rapida di una pagina","Conversione di un mockup in codice","Componenti per un design system"],
    pros: ["Codice di qualità, non generato a caso","Ottimo ponte tra design e sviluppo"],
    cons: ["Legato all'ecosistema React","Serve uno sviluppatore per l'integrazione finale"],
    popularity: 65,
    featured: false,
  },
  {
    slug: "windsurf",
    name: "Windsurf",
    tagline: "Editor AI con agente che segue il flusso di lavoro",
    description: "Alternativa diretta a Cursor, con un agente che tiene traccia di quello che stai facendo tra un file e l'altro e propone il passo successivo.",
    categories: ["sviluppo"],
    color: "#0B100F",
    url: "https://windsurf.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Pro 15 $/mese",
    features: ["Agente Cascade con memoria del contesto","Anteprima live delle modifiche","Compatibile con le estensioni VS Code","Distribuzione integrata"],
    useCases: ["Sviluppo full stack quotidiano","Riscrittura di moduli esistenti"],
    pros: ["Prezzo inferiore ai concorrenti diretti","Buona gestione del contesto tra i file"],
    cons: ["Ecosistema più piccolo","Aggiornamenti frequenti che cambiano le abitudini"],
    popularity: 58,
    featured: false,
  },
  {
    slug: "supabase",
    name: "Supabase",
    tagline: "Il database che sta dietro alle applicazioni generate con l'AI",
    description: "Postgres gestito con autenticazione, storage e API automatiche. È l'infrastruttura di fatto per i progetti costruiti con gli strumenti di generazione, incluso questo sito.",
    categories: ["sviluppo","dati"],
    color: "#3FCF8E",
    url: "https://supabase.com",
    pricing: "freemium",
    pricingNote: "Piano gratuito generoso · Pro 25 $/mese",
    features: ["Postgres gestito con API REST automatica","Autenticazione e permessi per riga","Storage per file","Funzioni serverless","Ricerca vettoriale con pgvector"],
    useCases: ["Base dati di un portale clienti","Archivio vettoriale per un chatbot aziendale","Backend di un'app generata con Lovable"],
    pros: ["Postgres vero: nessun vincolo tecnologico","Piano gratuito sufficiente per partire","Regioni europee disponibili"],
    cons: ["Serve capire i permessi per riga per non esporre dati","Costi che crescono con lo storage"],
    popularity: 70,
    featured: false,
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "L'AI dentro il posto dove l'azienda tiene le procedure",
    description: "Il valore non è la scrittura ma la ricerca: interroga in linguaggio naturale tutto quello che l'azienda ha già scritto, comprese le pagine che nessuno ricorda di aver creato.",
    categories: ["produttivita","contenuti","operations"],
    color: "#111111",
    url: "https://www.notion.com/product/ai",
    pricing: "freemium",
    pricingNote: "Incluso nei piani Business da 20 €/utente/mese",
    features: ["Ricerca AI su tutto lo spazio di lavoro","Connettori verso Slack, Drive e GitHub","Generazione e riscrittura in pagina","Compilazione automatica delle proprietà nei database","Agenti su base pianificata"],
    useCases: ["Manuale operativo interrogabile","Verbali di riunione strutturati","Wiki di prodotto aggiornata"],
    pros: ["Trova cose che nessuno ricordava","Nessuno strumento nuovo da adottare"],
    cons: ["Utile solo se in Notion c'è già contenuto","Il costo per utente pesa sui team grandi"],
    popularity: 77,
    featured: false,
  },
  {
    slug: "gamma",
    name: "Gamma",
    tagline: "Presentazioni e documenti generati e già impaginati",
    description: "Dai un tema o incolli un testo, e ottieni una presentazione impaginata bene. Per una PMI che deve produrre materiale commerciale senza un grafico è la scorciatoia più onesta.",
    categories: ["design","contenuti","produttivita","vendite"],
    color: "#7C3AED",
    url: "https://gamma.app",
    pricing: "freemium",
    pricingNote: "Gratis con crediti · Plus 10 $/mese",
    features: ["Generazione da testo o da file","Temi con identità di marca","Esportazione in PowerPoint e PDF","Pagine web pubblicabili","Analitiche sulle visualizzazioni"],
    useCases: ["Proposta commerciale impaginata in mezz'ora","Presentazione aziendale sempre aggiornata","Materiale per una fiera"],
    pros: ["Risultato presentabile senza competenze grafiche","Esportazione in formati standard"],
    cons: ["Estetica riconoscibile: si capisce che è Gamma","Controllo tipografico limitato"],
    popularity: 75,
    featured: false,
  },
  {
    slug: "granola",
    name: "Granola",
    tagline: "Appunti di riunione che si scrivono da soli",
    description: "Ascolta la riunione dal computer, senza bot che entrano nella call, e produce appunti strutturati con le azioni assegnate. Il dettaglio del bot assente conta più di quanto sembri con i clienti.",
    categories: ["produttivita","operations","vendite"],
    color: "#F97316",
    url: "https://www.granola.ai",
    pricing: "freemium",
    pricingNote: "Gratis fino a 25 riunioni · da 18 $/mese",
    features: ["Trascrizione senza bot nella chiamata","Appunti uniti alle note scritte a mano","Modelli per tipo di riunione","Ricerca su tutto lo storico"],
    useCases: ["Verbali dei comitati","Note delle call commerciali dentro il CRM","Passaggio di consegne tra colleghi"],
    pros: ["Nessun partecipante estraneo nella riunione","Appunti effettivamente leggibili"],
    cons: ["Solo su Mac e Windows","Serve comunque informare i partecipanti della registrazione"],
    popularity: 67,
    featured: false,
  },
  {
    slug: "fireflies",
    name: "Fireflies",
    tagline: "Registrazione e analisi delle chiamate commerciali",
    description: "Entra nelle riunioni, trascrive, e restituisce metriche: chi ha parlato quanto, quali obiezioni sono emerse, cosa è stato promesso. Utile a chi gestisce una rete vendita.",
    categories: ["produttivita","vendite"],
    color: "#1F4EF5",
    url: "https://fireflies.ai",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Pro 18 $/utente/mese",
    features: ["Trascrizione multilingua, italiano incluso","Analisi del parlato e delle obiezioni","Sincronizzazione con i CRM","Ricerca su tutto l'archivio chiamate"],
    useCases: ["Affiancamento dei commerciali junior","Estrazione delle obiezioni ricorrenti","Aggiornamento automatico delle opportunità"],
    pros: ["Buona resa sull'italiano","Integrazioni CRM solide"],
    cons: ["Il bot in chiamata è visibile a tutti","Consenso alla registrazione da gestire"],
    popularity: 62,
    featured: false,
  },
  {
    slug: "airtable",
    name: "Airtable AI",
    tagline: "Database operativo con l'AI dentro le colonne",
    description: "Una colonna che chiama un modello su ogni riga: classifica, riassume, traduce, estrae. È il modo più semplice per applicare l'AI a una tabella che l'azienda già usa.",
    categories: ["dati","operations","no-code"],
    color: "#18BFFF",
    url: "https://airtable.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Team 20 $/utente/mese",
    features: ["Campi AI applicati riga per riga","Automazioni interne","Interfacce per gli utenti finali","Sincronizzazione con fonti esterne"],
    useCases: ["Classificazione delle richieste in arrivo","Riassunto automatico dei feedback clienti","Traduzione di un catalogo prodotti"],
    pros: ["AI applicata a dati già strutturati","Interfacce utente senza sviluppo"],
    cons: ["Costo per utente elevato oltre il team ristretto","Limiti di record sui piani bassi"],
    popularity: 63,
    featured: false,
  },
  {
    slug: "julius",
    name: "Julius AI",
    tagline: "Analisi di fogli di calcolo a linguaggio naturale",
    description: "Carichi un Excel e fai domande. Restituisce grafici, statistiche e il codice usato per ottenerli, così il risultato è verificabile.",
    categories: ["dati"],
    color: "#2563EB",
    url: "https://julius.ai",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · da 20 $/mese",
    features: ["Domande in linguaggio naturale su file caricati","Grafici generati in automatico","Codice Python visibile","Modelli predittivi di base"],
    useCases: ["Analisi delle vendite per area e periodo","Individuazione dei clienti a rischio abbandono","Report mensile senza tabelle pivot"],
    pros: ["Nessuna competenza statistica richiesta","Il codice mostrato rende il risultato controllabile"],
    cons: ["Limiti sulla dimensione dei file","Dati caricati su server esterni: attenzione a quelli sensibili"],
    popularity: 55,
    featured: false,
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    tagline: "La qualità estetica più alta nella generazione di immagini",
    description: "Resta il riferimento quando l'immagine deve reggere il confronto con una produzione fotografica. Meno controllabile di altri, ma con una resa che gli altri non raggiungono.",
    categories: ["immagini","design","contenuti"],
    color: "#1B1B1B",
    url: "https://www.midjourney.com",
    pricing: "a pagamento",
    pricingNote: "Da 10 $/mese",
    features: ["Controllo dello stile con riferimenti","Coerenza tra personaggi","Editor con inpainting","Estensione dell'inquadratura"],
    useCases: ["Immagini per campagne pubblicitarie","Concept visivi per un prodotto","Copertine editoriali"],
    pros: ["Qualità estetica superiore","Comunità e materiale formativo abbondanti"],
    cons: ["Nessun piano gratuito","Testo dentro le immagini poco affidabile","Diritti d'uso da leggere con attenzione"],
    popularity: 78,
    featured: false,
  },
  {
    slug: "nano-banana",
    name: "Nano Banana",
    tagline: "Modifica di immagini per conversazione, con il testo che funziona",
    description: "Il modello di immagini di Google: la sua forza è la modifica mirata. Cambi il colore di un prodotto o il testo di un'insegna senza rigenerare tutto il resto.",
    categories: ["immagini","design","marketing"],
    color: "#FFB300",
    url: "https://gemini.google.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti dentro Gemini",
    features: ["Modifica conversazionale dell'immagine","Testo reso correttamente","Coerenza del soggetto tra più scatti","Fusione di più immagini"],
    useCases: ["Varianti colore di uno stesso prodotto","Scene di ambientazione per l'e-commerce","Grafiche con testo in italiano"],
    pros: ["Modifica chirurgica senza perdere il resto","Accessibile dal piano gratuito"],
    cons: ["Filigrana sui piani gratuiti","Meno controllo stilistico di Midjourney"],
    popularity: 81,
    featured: false,
  },
  {
    slug: "ideogram",
    name: "Ideogram",
    tagline: "Immagini generate con testo leggibile dentro",
    description: "Il problema storico dei generatori è il testo. Ideogram lo risolve meglio di tutti: loghi, insegne, poster e mockup con parole scritte correttamente.",
    categories: ["immagini","design","marketing"],
    color: "#1B1B1B",
    url: "https://ideogram.ai",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · da 8 $/mese",
    features: ["Resa affidabile del testo nelle immagini","Preimpostazioni tipografiche","Modifica per aree selezionate","Estensione dell'inquadratura"],
    useCases: ["Bozze di logo e marchi","Poster e materiale per punti vendita","Grafiche social con claim"],
    pros: ["Il migliore sul testo dentro l'immagine","Piano gratuito utilizzabile"],
    cons: ["Meno raffinato su scene fotorealistiche complesse"],
    popularity: 59,
    featured: false,
  },
  {
    slug: "canva",
    name: "Canva AI",
    tagline: "Grafica aziendale con generazione integrata",
    description: "Per chi in azienda produce materiale visivo senza essere un grafico, Canva resta lo strumento con il miglior rapporto tra risultato e tempo. Le funzioni AI accorciano solo la parte noiosa.",
    categories: ["design","marketing","contenuti"],
    color: "#00C4CC",
    url: "https://www.canva.com",
    pricing: "freemium",
    pricingNote: "Gratis · Pro 11,99 €/mese · Teams da 10 €/utente",
    features: ["Generazione di immagini e testi in pagina","Kit di marca con font e colori bloccati","Ridimensionamento automatico per ogni formato","Rimozione dello sfondo","Modelli di presentazione e social"],
    useCases: ["Post e caroselli per i canali aziendali","Cataloghi e listini impaginati","Materiale per eventi e fiere"],
    pros: ["Alla portata di chiunque","Il kit di marca tiene la coerenza visiva"],
    cons: ["Risultati riconoscibili se si usano i modelli così come sono","Funzioni AI a consumo"],
    popularity: 86,
    featured: false,
  },
  {
    slug: "figma",
    name: "Figma AI",
    tagline: "Progettazione di interfacce con generazione e passaggio al codice",
    description: "Lo standard per il design di interfacce, ora con generazione di bozze da prompt e traduzione diretta dei componenti in codice.",
    categories: ["design","sviluppo"],
    color: "#F24E1E",
    url: "https://www.figma.com",
    pricing: "freemium",
    pricingNote: "Gratis · piani da 12 $/utente/mese",
    features: ["Generazione di bozze da descrizione","Figma Make per prototipi funzionanti","Passaggio dei componenti al codice","Riordino automatico dei livelli"],
    useCases: ["Progettazione del sito prima dello sviluppo","Design system aziendale","Prototipi da mostrare al cliente"],
    pros: ["Standard di settore: chiunque sa usarlo","Collaborazione in tempo reale"],
    cons: ["Le funzioni AI sono ancora acerbe","Curva ripida per chi non fa design"],
    popularity: 73,
    featured: false,
  },
  {
    slug: "higgsfield",
    name: "Higgsfield",
    tagline: "Video e ritratti AI con controllo cinematografico dei movimenti",
    description: "Pensato per chi produce contenuti brevi: preimpostazioni di movimento camera, avatar coerenti tra un video e l'altro e resa estetica alta senza una troupe.",
    categories: ["video","immagini","contenuti"],
    color: "#FF5A1F",
    url: "https://higgsfield.ai",
    pricing: "freemium",
    pricingNote: "Crediti gratuiti · piani da 9 $/mese",
    features: ["Preimpostazioni di movimento camera","Avatar coerenti tra i video","Sincronizzazione labiale","Upscaling fino a 4K"],
    useCases: ["Reel per Instagram e TikTok","Spot brevi per campagne","Contenuti seriali con lo stesso volto"],
    pros: ["Controllo del movimento che gli altri non hanno","Ottimo per contenuti verticali seriali"],
    cons: ["Crediti consumati in fretta","Qualità variabile tra un modello e l'altro"],
    popularity: 60,
    featured: false,
  },
  {
    slug: "sora",
    name: "Sora",
    tagline: "Video generati da testo con audio sincronizzato",
    description: "Il modello video di OpenAI genera clip con dialoghi e ambiente sonoro coerenti. Per una PMI serve soprattutto a produrre spezzoni di contorno senza girare.",
    categories: ["video","contenuti"],
    color: "#10A37F",
    url: "https://sora.chatgpt.com",
    pricing: "a pagamento",
    pricingNote: "Incluso nei piani ChatGPT Plus e Pro",
    features: ["Video con audio e dialoghi sincronizzati","Cameo con soggetti ricorrenti","Remix di clip esistenti","Formati verticali e orizzontali"],
    useCases: ["Spezzoni di contorno per un video parlato","Concept di campagna prima della produzione","Contenuti social senza riprese"],
    pros: ["Audio generato insieme al video","Coerenza tra le inquadrature"],
    cons: ["Durata limitata delle clip","Restrizioni sui volti reali","Serve un abbonamento a pagamento"],
    popularity: 79,
    featured: false,
  },
  {
    slug: "veo",
    name: "Veo",
    tagline: "Il modello video di Google, con audio nativo",
    description: "Veo genera clip con dialoghi ed effetti sonori generati insieme all'immagine. È accessibile da Gemini, quindi non richiede nuovi contratti.",
    categories: ["video","contenuti"],
    color: "#4285F4",
    url: "https://labs.google/fx/tools/flow",
    pricing: "freemium",
    pricingNote: "Limitato nel piano gratuito · pieno con Google AI Pro e Ultra",
    features: ["Audio e dialoghi nativi","Controllo di inquadratura e movimento","Estensione di clip esistenti","Da immagine a video"],
    useCases: ["Spot brevi per i social","Animazione di scatti prodotto","Contenuti pubblicitari in prova"],
    pros: ["Qualità dell'audio generato","Accessibile dentro l'abbonamento Google"],
    cons: ["Crediti limitati","Filigrana sui piani bassi"],
    popularity: 76,
    featured: false,
  },
  {
    slug: "runway",
    name: "Runway",
    tagline: "Strumenti video AI per chi monta davvero",
    description: "Più che un generatore, una cassetta degli attrezzi: rimozione di oggetti, sostituzione di sfondi, trasferimento di stile e generazione. Pensato per il montaggio professionale.",
    categories: ["video","design"],
    color: "#111111",
    url: "https://runwayml.com",
    pricing: "freemium",
    pricingNote: "Crediti gratuiti · da 12 $/mese",
    features: ["Generazione da testo, immagine o video","Rimozione di oggetti dalle riprese","Controllo dei movimenti di camera","Trasferimento di stile"],
    useCases: ["Pulizia di riprese girate male","Effetti su materiale esistente","Video di prodotto animati"],
    pros: ["Strumenti di post-produzione veri","Buona integrazione nel flusso di montaggio"],
    cons: ["Curva di apprendimento reale","Crediti costosi sui progetti lunghi"],
    popularity: 68,
    featured: false,
  },
  {
    slug: "heygen",
    name: "HeyGen",
    tagline: "Avatar che parlano, doppiati in trenta lingue",
    description: "Scrivi il testo e un avatar lo pronuncia con la sincronizzazione labiale. Il caso d'uso serio è il doppiaggio: prendi un video in italiano e lo trasformi in dieci lingue mantenendo la voce.",
    categories: ["video","marketing","vendite","formazione"],
    color: "#6B4EFF",
    url: "https://www.heygen.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · da 24 $/mese",
    features: ["Avatar personali addestrati sul proprio volto","Doppiaggio con clonazione della voce","Sincronizzazione labiale multilingua","Video personalizzati in blocco"],
    useCases: ["Formazione interna in più lingue","Video commerciali personalizzati per prospect","Presentazione prodotto per mercati esteri"],
    pros: ["Il doppiaggio multilingua è convincente","Produzione in blocco di video personalizzati"],
    cons: ["L'effetto avatar resta percepibile","Serve consenso esplicito per usare volti reali"],
    popularity: 71,
    featured: false,
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    tagline: "Video di formazione aziendale con avatar, senza riprese",
    description: "Nato per la formazione interna delle grandi aziende: aggiorni il testo di una procedura e il video si rigenera, senza riconvocare nessuno davanti a una telecamera.",
    categories: ["video","formazione","marketing"],
    color: "#1B1F3B",
    url: "https://www.synthesia.io",
    pricing: "a pagamento",
    pricingNote: "Da 29 $/mese",
    features: ["Oltre 200 avatar in 140 lingue","Aggiornamento del video modificando il testo","Modelli di corso e quiz","Integrazione con le piattaforme formative"],
    useCases: ["Corso sulla sicurezza aggiornato ogni anno","Onboarding dei nuovi assunti","Comunicazioni interne multilingua"],
    pros: ["Manutenzione dei video quasi a costo zero","Conformità e governance curate"],
    cons: ["Prezzo alto per una PMI piccola","Registro visivo istituzionale, poco adatto ai social"],
    popularity: 56,
    featured: false,
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Sintesi vocale in italiano che non suona sintetica",
    description: "È il riferimento per la voce: l'italiano generato regge l'ascolto, la clonazione funziona con pochi minuti di campione, e le API si integrano dentro i centralini.",
    categories: ["voce","contenuti","customer-service"],
    color: "#111111",
    url: "https://elevenlabs.io",
    pricing: "freemium",
    pricingNote: "Gratis 10.000 caratteri/mese · da 5 $/mese",
    features: ["Clonazione della voce da pochi minuti di audio","Italiano con prosodia naturale","Agenti vocali conversazionali","Doppiaggio automatico","Effetti sonori generati"],
    useCases: ["Voce narrante per video aziendali","Messaggi del centralino sempre aggiornati","Audioguide e podcast interni"],
    pros: ["La resa in italiano è la migliore del mercato","API solide e documentate"],
    cons: ["Il consumo a caratteri pesa sui progetti lunghi","La clonazione richiede consenso documentato"],
    popularity: 87,
    featured: true,
  },
  {
    slug: "vapi",
    name: "Vapi",
    tagline: "Centralini AI che rispondono e prenotano al telefono",
    description: "Costruisci un agente telefonico che risponde, capisce la richiesta, controlla l'agenda e fissa l'appuntamento. Per officine, studi e ristoranti è il caso d'uso con il ritorno più immediato.",
    categories: ["voce","customer-service","vendite"],
    color: "#5D5FEF",
    url: "https://vapi.ai",
    pricing: "freemium",
    pricingNote: "Crediti di prova · a consumo da circa 0,05 $/minuto",
    features: ["Chiamate in entrata e in uscita","Interruzione naturale della conversazione","Chiamate a funzioni esterne durante la telefonata","Trasferimento all'operatore umano","Registrazione e trascrizione"],
    useCases: ["Prenotazioni telefoniche fuori orario","Conferma automatica degli appuntamenti","Primo filtro sulle chiamate in entrata"],
    pros: ["Ritorno misurabile fin dal primo mese","Costo al minuto inferiore a un operatore"],
    cons: ["Configurazione tecnica non banale","Obbligo di dichiarare che si parla con un sistema automatico"],
    popularity: 65,
    featured: false,
  },
  {
    slug: "retell",
    name: "Retell AI",
    tagline: "Agenti vocali con editor visuale e integrazioni pronte",
    description: "Alternativa a Vapi con un editor a diagramma di flusso: più accessibile a chi non scrive codice, con connettori già fatti verso i CRM più diffusi.",
    categories: ["voce","customer-service"],
    color: "#3B82F6",
    url: "https://www.retellai.com",
    pricing: "freemium",
    pricingNote: "Prova gratuita · a consumo da circa 0,07 $/minuto",
    features: ["Editor visuale delle conversazioni","Numeri telefonici inclusi","Integrazioni CRM native","Analitiche sulle chiamate"],
    useCases: ["Recall sui preventivi in sospeso","Sondaggi di soddisfazione telefonici","Qualificazione dei contatti in entrata"],
    pros: ["Più accessibile ai non sviluppatori","Analitiche già pronte"],
    cons: ["Meno flessibile su logiche particolari","Costo al minuto leggermente superiore"],
    popularity: 52,
    featured: false,
  },
  {
    slug: "suno",
    name: "Suno",
    tagline: "Musica originale generata da una descrizione",
    description: "Serve a risolvere un problema concreto e sottovalutato: la musica dei video aziendali senza rischi di diritti d'autore.",
    categories: ["voce","contenuti"],
    color: "#111111",
    url: "https://suno.com",
    pricing: "freemium",
    pricingNote: "Gratis con crediti · da 8 $/mese",
    features: ["Brani completi da descrizione testuale","Testi in italiano","Tracce separate per il montaggio","Uso commerciale sui piani a pagamento"],
    useCases: ["Sottofondo per video aziendali","Jingle per campagne","Sigla per un podcast"],
    pros: ["Nessun problema di licenze musicali","Risultati utilizzabili al primo tentativo"],
    cons: ["Uso commerciale solo dai piani a pagamento","Poco controllo sui dettagli dell'arrangiamento"],
    popularity: 58,
    featured: false,
  },
  {
    slug: "intercom-fin",
    name: "Intercom Fin",
    tagline: "L'agente di assistenza che chiude i ticket da solo",
    description: "Fin risponde alle richieste di assistenza basandosi sulla documentazione esistente e si paga a risoluzione, non a licenza. È il modello di prezzo più onesto della categoria.",
    categories: ["customer-service","agenti"],
    color: "#1F8DED",
    url: "https://www.intercom.com/fin",
    pricing: "a pagamento",
    pricingNote: "0,99 $ per conversazione risolta",
    features: ["Risposte ancorate alla base di conoscenza","Passaggio all'operatore quando serve","Multilingua, italiano incluso","Analitiche sul tasso di risoluzione"],
    useCases: ["Assistenza di primo livello sull'e-commerce","Risposte alle domande ricorrenti su spedizioni e resi","Supporto fuori orario"],
    pros: ["Si paga solo quando funziona","Non inventa: risponde dalla documentazione"],
    cons: ["Richiede una base di conoscenza già scritta bene","Costo per conversazione che pesa sui volumi alti"],
    popularity: 64,
    featured: false,
  },
  {
    slug: "tidio-lyro",
    name: "Tidio Lyro",
    tagline: "Chatbot AI per e-commerce e piccoli negozi online",
    description: "Pensato per chi vende online e non ha un reparto assistenza: si collega al catalogo, risponde su prodotti e spedizioni, e costa poco.",
    categories: ["customer-service","vendite"],
    color: "#294CDB",
    url: "https://www.tidio.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · Lyro da 39 $/mese",
    features: ["Collegamento diretto a Shopify e WooCommerce","Risposte sullo stato dell'ordine","Chat dal vivo con passaggio all'operatore","Multilingua"],
    useCases: ["Assistenza su un e-commerce piccolo","Recupero dei carrelli abbandonati","Domande su disponibilità e spedizioni"],
    pros: ["Installazione in un'ora su Shopify","Prezzo adatto a una piccola attività"],
    cons: ["Meno flessibile delle soluzioni su misura","Conteggio a conversazione"],
    popularity: 54,
    featured: false,
  },
  {
    slug: "hubspot-breeze",
    name: "HubSpot Breeze",
    tagline: "L'AI dentro il CRM: dati arricchiti e follow-up scritti",
    description: "Breeze lavora sul CRM che l'azienda ha già: completa le anagrafiche mancanti, scrive le email di ripresa e assegna un punteggio ai contatti in base al comportamento reale.",
    categories: ["vendite","marketing"],
    color: "#FF7A59",
    url: "https://www.hubspot.com",
    pricing: "freemium",
    pricingNote: "CRM gratuito · funzioni AI dai piani Professional",
    features: ["Arricchimento automatico delle anagrafiche","Punteggio predittivo sui contatti","Bozze di email personalizzate","Agente di assistenza sul sito","Riassunto automatico delle trattative"],
    useCases: ["Priorità sui lead da richiamare per primi","Sequenze di ripresa automatiche","Report commerciale senza compilazione manuale"],
    pros: ["Parte da un CRM gratuito e completo","Un unico ambiente per marketing e vendite"],
    cons: ["Le funzioni utili stanno nei piani alti","Costi che crescono in fretta"],
    popularity: 70,
    featured: false,
  },
  {
    slug: "apollo",
    name: "Apollo.io",
    tagline: "Banca dati di contatti B2B con sequenze automatiche",
    description: "Trovi le aziende target, i nomi giusti dentro quelle aziende, e mandi la sequenza. Da usare con attenzione: in Italia il contatto a freddo ha vincoli GDPR precisi.",
    categories: ["vendite","marketing"],
    color: "#2E5CE6",
    url: "https://www.apollo.io",
    pricing: "freemium",
    pricingNote: "Gratis con crediti · da 49 $/utente/mese",
    features: ["Oltre 200 milioni di contatti B2B","Filtri per settore, dimensione e tecnologia","Sequenze email automatiche","Verifica della validità degli indirizzi"],
    useCases: ["Costruzione di una lista prospect per settore","Ricerca dei decisori in aziende target","Campagne outbound strutturate"],
    pros: ["Banca dati ampia anche sull'Italia","Tutto in un unico strumento"],
    cons: ["Base giuridica del contatto a freddo da verificare con il DPO","Qualità dei dati italiani disomogenea"],
    popularity: 60,
    featured: false,
  },
  {
    slug: "clay",
    name: "Clay",
    tagline: "Arricchimento dati commerciali da cinquanta fonti insieme",
    description: "Metti una lista di aziende, Clay interroga decine di banche dati e ti restituisce fatturato, dipendenti, tecnologie usate e segnali di acquisto. Poi un modello scrive il messaggio.",
    categories: ["vendite","dati","marketing"],
    color: "#1A1A1A",
    url: "https://www.clay.com",
    pricing: "freemium",
    pricingNote: "Piano gratuito con crediti · da 149 $/mese",
    features: ["Oltre 100 fonti di arricchimento a cascata","Ricerca AI su ogni riga","Personalizzazione dei messaggi su dati reali","Integrazione con i CRM"],
    useCases: ["Segmentazione di un mercato per segnali di acquisto","Ricerca automatica su ogni prospect prima della chiamata","Pulizia e completamento del CRM"],
    pros: ["Profondità dei dati senza pari","Riduce ore di ricerca manuale"],
    cons: ["Prezzo alto per una piccola realtà","Configurazione iniziale complessa"],
    popularity: 63,
    featured: false,
  },
  {
    slug: "brevo",
    name: "Brevo",
    tagline: "Email marketing europeo con automazioni e AI",
    description: "Alternativa francese a Mailchimp, con server in Europa e prezzi tarati sulle piccole imprese. Le funzioni AI scrivono oggetti e segmentano le liste.",
    categories: ["marketing","vendite"],
    color: "#0B996E",
    url: "https://www.brevo.com",
    pricing: "freemium",
    pricingNote: "Gratis 300 email/giorno · da 9 €/mese",
    features: ["Automazioni su comportamento","Generazione di oggetti e contenuti","SMS e WhatsApp integrati","CRM incluso","Dati ospitati in Unione Europea"],
    useCases: ["Newsletter aziendale","Sequenze post-acquisto per e-commerce","Recupero dei carrelli abbandonati"],
    pros: ["Server in UE: conformità GDPR più semplice","Prezzo a email inviate, non a contatti"],
    cons: ["Editor meno raffinato dei concorrenti americani","Funzioni AI ancora essenziali"],
    popularity: 53,
    featured: false,
  },
  {
    slug: "opus-clip",
    name: "OpusClip",
    tagline: "Da un video lungo a dieci clip verticali pronte",
    description: "Prende un webinar o un'intervista e ne estrae i passaggi che funzionano da soli, con sottotitoli e inquadratura verticale già sistemata.",
    categories: ["video","contenuti","marketing"],
    color: "#6C3DF4",
    url: "https://www.opus.pro",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · da 9 $/mese",
    features: ["Selezione automatica dei passaggi migliori","Sottotitoli in italiano","Riquadratura verticale che segue il volto","Punteggio di potenziale virale"],
    useCases: ["Riuso di un webinar sui social","Clip da interviste e podcast","Contenuti brevi dal materiale già girato"],
    pros: ["Trasforma materiale esistente in contenuto nuovo","Sottotitoli italiani accurati"],
    cons: ["La selezione automatica va sempre rivista","Minuti limitati sul piano gratuito"],
    popularity: 66,
    featured: false,
  },
  {
    slug: "descript",
    name: "Descript",
    tagline: "Montaggio video modificando il testo della trascrizione",
    description: "Cancelli una frase nel testo e sparisce dal video. Per chi produce contenuti parlati e non ha un montatore, taglia i tempi di lavorazione a un terzo.",
    categories: ["video","contenuti"],
    color: "#2B2A5C",
    url: "https://www.descript.com",
    pricing: "freemium",
    pricingNote: "Gratis con limiti · da 24 $/mese",
    features: ["Montaggio dal testo trascritto","Rimozione automatica delle pause e degli intercalari","Correzione dello sguardo in camera","Clonazione della voce per correggere errori"],
    useCases: ["Montaggio di video parlati","Produzione di podcast","Pulizia di registrazioni di formazione"],
    pros: ["Il montaggio testuale è un cambio di paradigma","Rimuove gli intercalari senza intervento manuale"],
    cons: ["Trascrizione italiana meno precisa dell'inglese","Richiede caricamenti pesanti"],
    popularity: 61,
    featured: false,
  },];

export const ETICHETTE_PREZZO: Record<Prezzo, string> = {
  gratis: "Gratis",
  freemium: "Freemium",
  "a pagamento": "A pagamento",
};

export function logoTool(slug: string): string {
  return `/blog/tool/${slug}.png`;
}

export function categoriaPrincipale(t: Tool): string {
  return t.categories[0];
}

export function etichettaCategoriaTool(slug: string): string {
  return etichetta(CATEGORIE_TOOL, slug);
}

export function getTool(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

/** Categorie effettivamente popolate, nell'ordine della tassonomia. */
export function categorieToolAttive() {
  const usate = new Set(TOOLS.flatMap((t) => t.categories));
  return CATEGORIE_TOOL.filter((c) => usate.has(c.slug)).map((c) => ({
    ...c,
    count: TOOLS.filter((t) => t.categories.includes(c.slug)).length,
  }));
}

export function toolPerCategoria(slug: string): Tool[] {
  if (slug === "tutti") return [...TOOLS].sort((a, b) => a.name.localeCompare(b.name, "it"));
  if (slug === "popolari") return [...TOOLS].sort((a, b) => b.popularity - a.popularity);
  return TOOLS.filter((t) => t.categories.includes(slug)).sort((a, b) => b.popularity - a.popularity);
}

export function toolInEvidenza(n = 12): Tool[] {
  return [...TOOLS].sort((a, b) => Number(b.featured) - Number(a.featured) || b.popularity - a.popularity).slice(0, n);
}

/** Tool simili: stessa categoria principale, esclusi quelli già citati. */
export function toolSimili(t: Tool, n = 4): Tool[] {
  const principale = categoriaPrincipale(t);
  const punteggio = (x: Tool) =>
    x.categories.filter((c) => t.categories.includes(c)).length * 10 + x.popularity / 100;
  return TOOLS.filter((x) => x.slug !== t.slug && x.categories.some((c) => t.categories.includes(c)))
    .sort((a, b) => punteggio(b) - punteggio(a) || Number(b.categories[0] === principale) - Number(a.categories[0] === principale))
    .slice(0, n);
}
